name: NewTrends
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - alabaster=0.7.12
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.12
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - astroid=2.4.2
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.2.0
  - autopep8=1.5.4
  - babel=2.8.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.2.0
  - beautifulsoup4=4.9.3
  - blas=1.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.3
  - chardet=3.0.4
  - clangdev=5.0.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - clyent=1.2.2
  - colorama=0.4.3
  - conda=4.9.2
  - conda-build=3.18.11
  - conda-env=2.6.0
  - conda-package-handling=1.6.1
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - cryptography=3.1.1
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - docutils=0.16
  - easygui=0.98.1
  - entrypoints=0.3
  - fastcache=1.1.0
  - filelock=3.0.12
  - flake8=3.8.4
  - freetype=2.10.2
  - future=0.18.2
  - glob2=0.7
  - glpk=4.65
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.2
  - intervaltree=3.1.0
  - ipopt=3.13.3
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=5.6.4
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - keyring=21.4.0
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - libarchive=3.4.2
  - libblas=3.8.0
  - libflang=5.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - liblief=0.10.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.1.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mccabe=0.6.1
  - menuinst=1.4.16
  - metis=5.1.0
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mpmath=1.1.0
  - msys2-conda-epoch=20160418
  - mumps-seq=5.2.1
  - navigator-updater=0.2.1
  - nbclient=0.5.0
  - nbconvert=6.0.7
  - nbformat=5.0.7
  - nest-asyncio=1.4.1
  - nose=1.3.7
  - notebook=6.1.4
  - numpy=1.19.1
  - numpy-base=1.19.1
  - numpydoc=1.1.0
  - olefile=0.46
  - openmp=5.0.0
  - openssl=1.1.1i
  - packaging=20.4
  - pandas=1.1.2
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - paramiko=2.7.2
  - parso=0.7.0
  - pathtools=0.1.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.3
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - ply=3.11
  - powershell_shortcut=0.0.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - psutil=5.7.2
  - py-lief=0.10.1
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pydocstyle=5.1.1
  - pyflakes=2.2.0
  - pygments=2.7.1
  - pylint=2.6.0
  - pynacl=1.4.0
  - pyomo=5.7.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - python-libarchive-c=2.9
  - python_abi=3.8
  - pytz=2020.1
  - pyutilib=6.0.0
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=1.0.1
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - requests=2.24.0
  - retrying=1.3.3
  - rope=0.18.0
  - rtree=0.9.4
  - ruamel_yaml=0.15.87
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=50.3.0
  - sip=4.19.13
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.2.2
  - soupsieve=2.0.1
  - sphinx=3.2.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.1.5
  - spyder-kernels=1.9.4
  - sqlite=3.33.0
  - sympy=1.6.2
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - tqdm=4.50.0
  - traitlets=5.0.4
  - ujson=4.0.1
  - urllib3=1.25.10
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - watchdog=0.10.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xlrd=1.2.0
  - xlsxwriter=1.3.6
  - xmltodict=0.12.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5    

# open conda prompt here and type the following comand:
#  conda env create -f environment.yml
